# .github/workflows/workflow-validation.yml
name: Workflow Validation

on:
  push:
    branches:
      - master
      - develop
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - '.github/workflows/**'

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
