name: Terraform Workflow

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'terraform/**'
  issue_comment:
    types: [created]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan
        continue-on-error: true

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: ${{ needs.terraform-plan.result == 'success' && github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, '#terraform apply') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Terraform Apply
        run: ./project/scripts/apply_terraform.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output Instruction
        run: echo "After reviewing the Terraform plan, type #terraform apply in a comment to trigger the apply process."
